#!/usr/bin/env python3
"""
xxops-linkspeed-peers.py -- generate per-host link-speed configs.

Runs on the MONITOR. Neither a node nor a gateway can address the other on
the tailnet unaided: a gateway holds only its node's dyndns name, and
Tailscale knows hosts by their vmi names rather than their xx labels. The
monitor is the only thing that knows both halves, so it derives the pairing
here and each host is handed its own answer.

Writes one file per host into a staging directory. Distribution is a separate
step -- this only decides and writes locally, so it can be run and inspected
without touching anything else.

  health   peer = this node's own gateway. The production path.
  capacity peer = EVERY other node, comma separated. The node picks one
                  per day, so rotation costs no redistribution. Written
                  only when there are enough nodes for it to mean
                  something -- see MIN_NODES_FOR_CAPACITY.

Only needed if you have enough hosts that typing addresses by hand is worse
than running this. With a handful of validators, pass the addresses to
xxops-linkspeed-install.sh directly instead.

Usage:  xxops-linkspeed-peers.py               # dry run, prints what it would write
        xxops-linkspeed-peers.py --apply       # writes the staging directory
"""

import json
import os
import sys

AGENTS = os.environ.get("XXOPS_AGENTS", "/var/lib/xxops/agents.json")
STAGE = os.environ.get("XXOPS_STAGE", "/var/lib/xxops/linkspeed-conf")

APPLY = "--apply" in sys.argv

# Fewer nodes than this and the capacity test is switched off
# entirely. Three gives at least two possible peers, so rotation can
# tell a slow node from a slow partner. Two gives one peer forever
# and a number nobody can attribute.
MIN_NODES_FOR_CAPACITY = 3


def pair_gateway(node, gateways):
    """The app pairs a node to the shortest gateway name that STARTS WITH the
    node's name -- a node "foo" pairs with "foos" or "foo_gw", whichever name
    is shorter. Mirror that exactly rather than inventing a second rule, or
    the spec panel and the test would disagree about which gateway a node
    belongs to."""
    cands = sorted((g for g in gateways if g.startswith(node)), key=len)
    return cands[0] if cands else None


def main():
    try:
        with open(AGENTS, encoding="utf-8") as fh:
            agents = json.load(fh)
    except Exception as e:
        print("cannot read %s: %s" % (AGENTS, e))
        return every nodes, gateways = {}, {}
    for name, info in sorted(agents.items()):
        if not isinstance(info, dict):
            continue
        ip = info.get("ip")
        if not ip:
            continue
        if info.get("role") == "node":
            nodes[name] = ip
        elif info.get("role") == "gateway":
            gateways[name] = ip

    if not nodes:
        print("no nodes in %s -- refusing to write empty configs" % AGENTS)
        return 1

    files, unpaired = {}, []

    for name, ip in nodes.items():
        lines = ["# generated by xxops-linkspeed-peers.py -- do not hand edit",
                 "LISTEN_IP=%s" % ip]

        gw = pair_gateway(name, gateways)
        if gw:
            lines.append("GATEWAY_PEER=%s" % gateways[gw])
        else:
            # No gateway found. Leave GATEWAY_PEER out entirely rather than
            # guessing: the script treats a missing peer as "no test to run"
            # and exits clean, which is correct. A wrong peer would produce a
            # confident wrong number instead.
            unpaired.append(name)

        # Every capacity reading is min(both ends), so it only means
        # something once a node has met different partners on
        # different days. Below the threshold, write no NODE_PEER and
        # let the test skip cleanly rather than publish a figure that
        # cannot be attributed to either end.
        others = [v for k, v in nodes.items() if k != name]
        if len(nodes) >= MIN_NODES_FOR_CAPACITY and others:
            lines.append("NODE_PEER=%s" % ",".join(others))

        files["%s.conf" % name] = "\n".join(lines) + "\n"

    # Gateways are listeners only. They get a bind address and nothing else,
    # so the test script on them has no peer and does nothing.
    for name, ip in gateways.items():
        files["%s.conf" % name] = (
            "# generated by xxops-linkspeed-peers.py -- do not hand edit\n"
            "LISTEN_IP=%s\n" % ip)

    print("%d nodes, %d gateways -> %d config files"
          % (len(nodes), len(gateways), len(files)))
    if len(nodes) < MIN_NODES_FOR_CAPACITY:
        print("CAPACITY TEST OFF: fewer than %d nodes. Link speed to "
              "each node's own gateway still runs. Node-to-node "
              "capacity needs more nodes before a slow reading can be "
              "blamed on one end rather than the other."
              % MIN_NODES_FOR_CAPACITY)
    if unpaired:
        print("NO GATEWAY MATCHED for: %s (health test will be skipped there)"
              % ", ".join(unpaired))

    if not APPLY:
        sample = sorted(k for k in files if k[:-5] in nodes)[:1]
        for k in sample:
            print("\n--- %s ---\n%s" % (k, files[k]))
        print("Dry run. Rerun with --apply to write %s" % STAGE)
        return 0

    os.makedirs(STAGE, exist_ok=True)
    byip = os.path.join(STAGE, "by-ip")
    os.makedirs(byip, exist_ok=True)

    def put(path, content):
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)

    all_ips = dict(nodes)
    all_ips.update(gateways)

    for fname, content in files.items():
        put(os.path.join(STAGE, fname), content)
        # Also index by tailnet IP. A host installing itself knows its own
        # address from `tailscale ip -4` but NOT its xxOps label -- the label
        # lives in the monitor's discovery, not on the host. Indexing by IP is
        # what lets one identical install command work on every machine.
        ip = all_ips.get(fname[:-5])
        if ip:
            put(os.path.join(byip, "%s.conf" % ip), content)

    # Anything left from a previous run for a host that no longer exists.
    # Report it; do not delete. A vanished host is more likely a discovery
    # blip than a decommission, and deleting its config silently stops its
    # tests.
    stale = [f for f in os.listdir(STAGE)
             if f.endswith(".conf") and f not in files]
    if stale:
        print("STALE (host no longer in agents.json, left in place): %s"
              % ", ".join(sorted(stale)))

    print("wrote %d files to %s" % (len(files), STAGE))
    return 0


if __name__ == "__main__":
    sys.exit(main())
